version: '3.8'

services:
  # angular-app:
  #   build: ./frontend
  #   ports:
  #     - "8080:80"
  #   networks:
  #     - its_network
  
  angular-app:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "4200:4200"
      - "49153:49153"
    volumes:
      - ./frontend/its_ui/src:/app/src
    networks:
      - its_network

  fastapi-backend:
    restart: always
    build: ./api
    command: python main.py
    environment:
      db_pwd: ${DB_SERVICE_PW?}
    ports:
      - "8888:8000"
    depends_on:
      - mongodb
    networks:
      - its_network

  mongodb:
    image: mongo:4.4.6
    environment:
      #Credentials for The root user of the db
      #Store credenials in a file called .env
      MONGO_INITDB_ROOT_USERNAME: useradmin
      MONGO_INITDB_ROOT_PASSWORD: ${DB_ROOT_PW?}
      # Service pw will be known by the backend
      DB_SERVICE_PW: ${DB_SERVICE_PW?}
    volumes:
      - mongodb_data:/data/db
      - ./database_scripts/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
    command:
      - mongod
    ports:
      - "27017:27017"
    networks:
      - its_network

networks:
  its_network:
    driver: bridge

volumes:
  mongodb_data:
