version: '3.8'

services:
  ollama:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "11434:11434"

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]